### ISSUE TITLE
NumberFormatException on a beta app

### ISSUE THREAD

**Issue by Devofure** [robohorse/gpversionchecker#1]
Hi, 
I have a beta app with a versionName 1.2.0-beta7 and now the app doesn't crash but it shutsdown without trowing an Exception, it only logs it.
Shouldn't be better to check the versionCode  instead of the versionName? 

This is what I get:
`java.lang.NumberFormatException: Invalid int: "120-beta7
at java.lang.Integer.invalidInt(Integer.java:138)
at java.lang.Integer.parse(Integer.java:410)
at java.lang.Integer.parseInt(Integer.java:367)
at com.robohorse.gpversionchecker.VersionCheckerService.obtainDataFromGooglePlayWithException(VersionCheckerService.java:81)
...
`

**Comment by robohorse** [comment]
Hi, thanks for your feedback.

"Shouldn't be better to check the versionCode instead of the versionName?"

No, we cant do it, because this information is not available in the html-page of application. Only this is available: 

``` html
<div class="title">Current Version</div> <div class="content" itemprop="softwareVersion"> 1.0.3 </div> 
```

But, i will change the rule of version comparation to String equals. I think, that it will be correct, because user(not developer) will never has version, that will greatest, than google play version and his "softwareVersion" must be equals to google play version, else he just has lower version of application. 

I fix it in an hour.

**Comment by robohorse** [comment]
Done.
Please change dependency to

``` gradle
compile 'com.robohorse.gpversionchecker:gpversionchecker:1.0.3'
```

**Comment by Devofure** [comment]
Hi, 
Thanks for the quick fix.

 I'm getting ExceptionInInitializerError in the live beta app, but not in the debug app:
`java.lang.ExceptionInInitializerError
at org.a.b.k.a(Unknown Source)
at org.a.b.l.<clinit>(Unknown Source)
at org.a.b.f.<init>(Unknown Source)
at org.a.b.e.<init>(Unknown Source)
at org.a.c.dh.b(Unknown Source)
at org.a.c.dh.a(Unknown Source)
at org.a.c.b.a(Unknown Source)
at org.a.c.ad.a(Unknown Source)
at org.a.a.a.a(Unknown Source)
at org.a.a.i.e(Unknown Source)
at org.a.a.e.a(Unknown Source)
at com.robohorse.gpversionchecker.VersionCheckerService.b(Unknown Source)
at com.robohorse.gpversionchecker.VersionCheckerService.a(Unknown Source)
at com.robohorse.gpversionchecker.VersionCheckerService.onHandleIntent(Unknown Source)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.NullPointerException: in == null
at java.util.Properties.load(Properties.java:246)
at org.a.b.k.d(Unknown Source)
at org.a.b.k.<clinit>(Unknown Source)`

its Ok to logg the error but it shouldn't crash the app.

**Comment by robohorse** [comment]
The major problem is conflict of proguard and jsoup library.
Add the following to proguard-project.txt:

``` gradle
-keep public class org.jsoup.** {
public *;
}
```

**Comment by Devofure** [comment]
Hi  thanks, I hope it works when its release, Another thing, when I override the gpvch_dialog_bg_color, the dialog content change color but not the title background or action background.
is there another way to change those colors?

![image](https://cloud.githubusercontent.com/assets/7500992/13904568/6dd14fbe-eea5-11e5-91cb-3782f71180ff.png)

Thanks for you time.

**Comment by robohorse** [comment]
Yes, you can use custom themes for dialog window (something like this http://stackoverflow.com/questions/29797134/how-to-use-and-style-the-new-alertdialog-from-appcompat-22-1-and-above).

But you are right - that is another bug )). I will fix it today by removing gpvch_dialog_bg_color or making full theme on its base

Also, you can test proGuard on debug builds by adding following into your build.gradle

``` gradle
 buildTypes {
        debug{
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by robohorse** [comment]
I removed the gpvch_dialog_bg_color property, because it can conflict with global app styles. Now you can styling your dialog window by using app styles.
Please change dependency to

``` gradle
compile 'com.robohorse.gpversionchecker:gpversionchecker:1.0.4'
```
