### ISSUE TITLE
NumberFormatException when parsing version string in VersionDataProvider

### ISSUE THREAD

**Issue by jinaiOS** [robohorse/gpversionchecker#38]
# Description:
I encountered a NumberFormatException when using the gpversionchecker library. The exception occurs when the library attempts to parse an empty string as an integer.

# Steps to Reproduce:

Add the gpversionchecker library to the project.
Configure the library as described in the documentation.
Trigger the version check process.

# Expected Behavior:
The library should handle empty strings gracefully and not attempt to parse them as integers.

# Actual Behavior:
A NumberFormatException is thrown with the following stack trace:

```
java.lang.NumberFormatException: For input string: ""
    at java.lang.Integer.parseInt(Integer.java:807)
    at java.lang.Integer.parseInt(Integer.java:915)
    at com.robohorse.gpversionchecker.provider.VersionDataProvider.obtainDataFromGooglePlay(VersionDataProvider.kt:25)
    at com.robohorse.gpversionchecker.executor.SyncExecutor$startSync$1.run(SyncExecutor.kt:35)
    at java.lang.Thread.run(Thread.java:1012)
```

## Thank you for creating such a great library!

**Comment by robohorse** [comment]
Hey @jinaiOS , thanks a lot for your report. Unfortunately this project is deprecated. Please use the official In-app updates library https://developer.android.com/guide/playcore/in-app-updates
